config/routes.rb
Rails.application.routes.draw do


	root 'top#home'

	get '/top/about' => 'top#about'



	devise_for :users
  resources :books,only:[:new,:create,:index,:show,:destroy, :edit, :update]
  resources :users,only:[:index,:show,:update,:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :body, length: { maximum: 200}
	validates :body, presence: true
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         attachment :profile_image

validates :introduction, length: {maximum: 50}
validates :name, length: {maximum: 20}
validates :name, length: {minimum: 2}
validates :name, presence: true

end
# validates :introduction, length: { maximum: 50}, on: :create
# validates :name, length: {maximum: 20}, on: :create
# validates :name, length: {minimum: 2}, on: :create
# validates :name, presence: true, on: :create

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully"
    user_path(@user.id)
    @user = User.find(current_user.id)
  end

 
  def after_sign_in_path_for(resource)
    flash[:notice] = "signed in successfully"
   	user_path(current_user.id)
    
  end

  def after_sign_out_path_for(resource)
     flash[:notice] = "sgined out successfully"
     root_path
  end
  



  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy, :index, :show]
  before_action :correct_user, only: [:edit, :update]


  def new
    @post_book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def create
    @user = User.find(current_user.id)
    @post_book = Book.new(book_params)
    @post_book.user_id = current_user.id
    if @post_book.save
      flash[:notice] = "successfully"
    redirect_to "/books/#{@post_book.id}"
    else
      @books = Book.all
    render :index
  end
  end
 
  def show
    @post_book = Book.new
    @books = Book.all
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @current_user = User.find(current_user.id)

  end

  def index
    @books = Book.all
    @post_book = Book.new
    @user = User.find(current_user.id)
  end


  def edit
    @post_book = Book.find(params[:id])
    @user = User.find(current_user.id)
  end

  def update
    @post_book = Book.find(params[:id])
    if @post_book.update(book_params)
      flash[:notice] = "successfully"
     redirect_to book_path(@post_book.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @post_book = Book.find(params[:id])
    @post_book.destroy
    redirect_to books_path
  end

  private

  def book_params
  params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_user
  @book = current_user.books.find_by(id: params[:id])
    unless @book
      redirect_to books_path
    end
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController

	def home
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, only: [:edit, :update,:index, :show]
	before_action :correct_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
		@books = @user.books .reverse_order
		@post_book = Book.new
	end

	def index
		@users = User.all
		@post_book = Book.new
		@user = User.find(current_user.id)
	end

	def edit
		@user = User.find(current_user.id)
	end


	def update
		@user = User.find(current_user.id)
    	if @user.update(user_params)
    	redirect_to "/users/#{@user.id}", notice: "You have updated successfully."
    	else
    	render :edit
		end
	end

	private

	def user_params
	    params.require(:user).permit(:name, :profile_image, :introduction)
	end

	def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
			<%= attachment_image_tag @user, :profile_image,size: "100x100",format: 'jpeg', fallback:"no_image.jpg" %>
	<table class="table">
		<tr>
			<th>name</th>
			<th class="user_list"><%= @user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th class="user_list"><%= @user.introduction %></th>

	</table>
		<div class="setting">
		<%=link_to '', edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_7041" %>
	    </div>


	<%= form_for(@post_book) do |f| %>
		<h2  class="new-book">New book</h2>
			<div class="row">
				<h4>Title</h4>
					<%=f.text_field :title, :class => 'col-xs-12'  %>
			</div>
			<div class="row">
				<h4>body</h4>
					<%=f.text_area :body, :class => 'col-xs-12' %>
			</div>
			<div class="action-row row">
				<%= f.submit "Create Book", :class => "col-xs-12 btn btn-primary" %>
			</div>
	<% end %>
</div>

app/views/books/edit.html.erb
<div class="body">
    <div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<% if @post_book.errors.any? %>
				  <div id="error_explanation">
				    <h2><%= @post_book.errors.count %>errors prohibited this obj from being saved: </h2>
				    <ul>
				    <% @post_book.errors.full_messages.each do |msg| %>
				      <li><%= msg %></li>
				    <% end %>
				    </ul>
				  </div>
				<% end %>

				<h1>Editing Book</h1>
<%= form_for(@post_book) do |f| %>
          <div class="field">
            <%= f.label :title %>
                <%= f.text_field :title, class: "col-xs-12" %>
          </div>
          <div class="field">
              <%= f.label :body %>
                  <%= f.text_field :body, class: "col-xs-12 opinion_field"%>
          </div>

          <div class="action">
          <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
          </div>
        <% end %>
          <div class="under-row">
        <%= link_to 'show', book_path(@post_book) %> | <a href="/books">back</a>
          </div>
			</div>


		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="body">
    <div class="container">
	<div class="row">
		<%= render'books/list' %>
		<% if @post_book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @post_book.errors.count %>errors prohibited this obj from being saved:</h2>
 
    <ul>
    <% @post_book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
			<div class="col-xs-9">
				<h2>Books</h2>
					<table class="table  table-hover">
						<thead>
							<tr>
								<th></th>
								<th>Title</th>
								<th>Opinion</th>
							</tr>
						</thead>
					    		</th>
						<% @books.each do |book| %>
					    	<tr>
					    		<th><%= attachment_image_tag book.user, :profile_image,size: "40x40",format: 'jpeg', fallback:"no_image.jpg" %>
					    		</th>
								<th> <%=link_to book.title, "/books/#{book.id}" %>

								</th>
								<th><%= book.body %></th>
							</tr>
						<% end %>
					</table>
			</div>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<div class="body">
    <div class="container">
		<% flash.each do |key, value| %>
	    <%= content_tag(:div, value, class: "#{key}") %>
	    <% end %>
<!-- form_for -->
	<div class="row">
		<%= render'books/list' %>
			<div class="col-xs-9">
				<h2>Books</h2>
					<table class="table  border-top">
						<thead>
							<tr>
								<th>Title</th>
								<th>Body</th>
							</tr>
						</thead>
						<% @books.each do |book| %>
							<tr>
								<th><%= attachment_image_tag @user, :profile_image,size: "40x40",format: 'jpeg', fallback:"no_image.jpg" %></th>
								<th><%=link_to book.title, book_path(book) %></th>
								<th><%= book.body %>n</th>
							</tr>
						<% end %>
					</table>
			</div>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="body">
    <div class="container">
	<div class="row">
		<%= render'books/list'%>
			<div class="col-xs-9">
				<h2>Book details</h2>
					<table class="table">
					    <tr>
					    	<th><a><%= attachment_image_tag @book.user, :profile_image,size: "40x40",format: 'jpeg', fallback:"no_image.jpg" %><br><%= link_to @book.user.name, user_path(@book.user_id) %> </a>
					    </th>
							<th class="book_list"><%= @book.title %></th>
							<th class="book_list"><%= @book.body %></th>
								<% if @book.user == current_user %>
								<th><%= link_to 'edit', edit_book_path(@book), class: "btn btn-info book_list" %></th>
									<th><%= link_to 'destroy', "/books/#{@book.id}", method: :delete, data: { 'confirm' =>  '本当に削除しますか？' }, class: "btn btn-danger book_list destroy" %><th>
								<% end %>
					</table>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<! DOCTYPE html>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset ="utf-8">
  <title>Bookers</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%=javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>



<body>
        <header class="navbar navbar-fixed-top navbar-inverse">
          <div class="container">

            <nav class="nav navbar navbar-left">
              <span>Bookers</span>
            </nav>

            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li><%= link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home home"%></li>
                    <li><%= link_to ' Users', users_path, class: "glyphicon glyphicon-user users" %> </li>
                    <li><%= link_to ' Books', books_path, class: "glyphicon glyphicon-book books" %></li>
                    <li><%= link_to ' Log out', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
                <% else %>
                    <li><%= link_to 'Home',root_path, class: "glyphicon glyphicon-home home" %></li>
                    <li><%= link_to 'About', "/home/about", class: "glyphicon glyphicon-link about" %></li>
                    <li><%= link_to 'Sign up', new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
                     <li><%= link_to 'Log in', new_user_session_path,  class: "glyphicon glyphicon-log-in sign_in" %></li>
                <% end %>
            </ul>
          </div>
        </header>

        <div class="container" style= "margin-top: 50px;">
          <% if flash[:notice] %>
          <%= flash[:notice] %>
          <% end %>
          <%= yield %>
        </div>
<footer>
<div class="container">
<div class="row">
<div class="col-xs-3 col-xs-offset-9">
<p class="copy-right">CopyRight Infratop.inc</p>
</div>
</div>
</div>

</body>
<html>

app/views/top/about.html.erb
<div class="body">
<div class="container">
		<h1>Welcome to 
		<p class="glyphicon glyphicon-book">
				<strong>Bookers</strong>!</p>
		</h1>
	</div>
</div>

app/views/top/home.html.erb
<div class="body">
	<div class="container">
		<p id="notice"><%= notice %></p>
		<div class="row">
			<div class="col-md-offset-3 col-md-6">
				<h1>Welcome to 
					<p class="glyphicon glyphicon-book">
						<strong>Bookers</strong>  !!
					</p>
					
				</h1>
				<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
				<p>you can share and exchange your opinions , inpressions , and emotions</p>
				<p>about varioius books!</p>
				</p>
				<div class="row">
					<a class="log-in col-xs-offset-1 col-xs-10 btn btn-info" href="/users/sign_in">Log in</a>
				</div>
				<div class="row">
					<a class="sign-up col-xs-offset-1 col-xs-10 btn btn-success" href="/users/sign_up">Sign up</a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">

          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= @user.errors.count %> error prohibited this obj from being saved: 
              </h2>
              <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        <h2>User info</h2>

        <%= form_for(@user) do |f| %>

        <div class="field"> 
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true, autocomplete: @user.name %>
        </div>

        <div class="field">
          <label>Image</label>
          <%= f.attachment_field :profile_image, class: "user-edit-form" %>
        </div>


        <div class="field">
          <label>Introduction</label>
          <%= f.text_field :introduction, class: "intorduction-edit-form" %>
        </div>
        

        <div class="actions">
          <%= f.submit "Update User" %>
        </div>
        
        <% end %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
    <div class="container">
	<div class="row">
		<%= render'books/list' %>
			<div class="col-xs-9">
				<h2>Users</h2>
					<table class="table  table-hover">
						<thead>
							<tr>
								<th>image</th>
								<th>name</th>
							</tr>
						</thead>
					    		</th>
						<% @users.each do |user| %>
					    	<tr>
					    		<th>
					    			<%= link_to user_path(user) do %>

					    			<%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback:"no_image.jpg", size:"40x40" %>
					    			<% end %>
					    		</th>
								<th> <%= user.name %>

								</th>
								<th><%=link_to 'show', "/users/#{user.id}" %></th>
							</tr>
						<% end %>
					</table>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <%= render'books/list' %>
      <!-- <p id="notice"><%= notice %></p> -->
      <div class="col-xs-9">
        <h2>Books</h2>
          <table class="table  table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
                  </th>
            <% @books.each do |book| %>
                <tr>
                  <th><%= attachment_image_tag @user, :profile_image,size: "40x40",format: 'jpeg', fallback:"no_image.jpg" %>
                  </th>
                <th> <%=link_to book.title, "/books/#{book.id}" %>

                </th>
                <th><%= book.body %></th>
              </tr>
            <% end %>
          </table>
      </div>
    </div>
  </div>
</div>